######## In this file we define symmetry groups to reduce the number of Susceptibilities we have to calculate
import Base.==
import Base.^

"""
    sym_element

A symmetry element representing a geometric transformation that combines
an orthogonal transformation with a translation.

# Fields
- `gMat::Matrix{Float64}`: Orthogonal transformation matrix
- `gVec::Vector{Float64}`: Translation vector

# Mathematical Description
For a point `r`, the action of a symmetry element `g` is:
    g(r) = gMat * r + gVec

# Constraints
- `gMat` must be orthogonal (inverse equals transpose)
- `gMat` must be non-singular (determinant ≠ 0)

# Examples
```julia
# Create a reflection across y-axis with translation
g = sym_element([-1.0 0.0; 0.0 1.0], [1.0, 0.0])

# Create a 90-degree rotation around origin
g = sym_element([0.0 -1.0; 1.0 0.0], [0.0, 0.0])
```

# See Also
- [`sym_group`](@ref): Groups of symmetry elements

"""
mutable struct sym_element
    gMat    ::Matrix{Float64}
    gVec    ::Vector{Float64}
    function sym_element(gMat,gVec)

        if abs(det(gMat)) < 1e-10
            throw(error("gMat is singular (not invertible or orthogonal)"))
        elseif inv(gMat) ≈ transpose(gMat)
            return new(gMat,gVec)
        else
            throw(error("gMat is not orthogonal"))
        end
    end
end

"""
    sym_group

Represents a symmetry group consisting of a collection of symmetry elements.

# Fields
- `n_elements::Int`: Number of symmetry elements in the group
- `elements::Vector{sym_element}`: Vector of symmetry elements. See [`sym_element`](@ref).

# Examples
```julia
# Create identity and reflection elements
id = sym_element([1.0 0.0; 0.0 1.0], [0.0, 0.0])
ref = sym_element([-1.0 0.0; 0.0 1.0], [0.0, 0.0])

# Create a group with these elements
G = sym_group([id, ref])
```
"""
mutable struct sym_group
    n_elements   ::Int                 # Number of symmetry elements in the group
    elements     ::Vector{sym_element} # Vector of symmetry elements

    function sym_group(data::Vector{sym_element})
        return new(length(data), data)
    end
end

"""
    translation_group

Represents a group of translational symmetries defined by a basis.

# Fields
- `basis::Matrix{Float64}`: Matrix where each column represents a basis vector 
  for the translation lattice

# Description
Translation groups define the periodicity of a lattice. The basis vectors
define a unit cell, and the full lattice is generated by translations
of points in the unit cell by integer combinations of the basis vectors.

# Examples
```julia
# Define a square lattice translation group
T = translation_group([(1.0, 0.0), (0.0, 1.0)])

# Define a hexagonal lattice translation group
a = 1.0
T_hex = translation_group([(a, 0.0), (a/2, a*sqrt(3)/2)])
```
"""
mutable struct translation_group
    basis   ::Matrix{Float64}  # Columns are translation basis vectors

    function translation_group(vec_of_tuples::Vector{<:Tuple})
       return new(hcat(collect.(vec_of_tuples)...))
    end
end



"""
    is_element(g, G) -> Bool

Check if symmetry element `g` is part of symmetry group `G`.

# Arguments
- `g::sym_element`: The symmetry element to check. See [`sym_element`](@ref).
- `G::sym_group`: The symmetry group to search in. See [`sym_group`](@ref).

# Returns
- `Bool`: `true` if `g` is found in `G`, `false` otherwise

# Examples
```julia
if is_element(g, G)
    println("Element is in the group")
end
```

"""
function is_element(g::sym_element, G::sym_group)::Bool
    for g2 in G.elements
        if g == g2
            return true
        end
    end
    return false
end

"""
    floor_tol(x; tol=1e-8) -> Int

Version of `floor(Int, x)` but with a tolerance to counter floating point errors.

# Arguments
- `x::Float64`: Input float value
- `tol::Float64=1e-8`: Tolerance for rounding near integers

# Returns
- `Int`: Integer part, accounting for tolerance near integer boundaries

# Examples
```julia
floor_tol(3.999999)  # Returns 3
floor_tol(3.000001)  # Returns 3
floor_tol(3.99999999) # Returns 4
```
"""
function floor_tol(x::Float64; tol=1e-8)
    int_part = floor(Int, x)
    if x - int_part > 1 - tol
        return int_part + 1
    elseif x - int_part < tol - 1
        return int_part - 1
    else
        return int_part
    end
end

"""
    mod!(g, T)

Modifies `g.gVec` so it's within the unit cell defined by translation group `T`.

# Arguments
- `g::sym_element`: Symmetry element to modify. See [`sym_element`](@ref).
- `T::translation_group`: Translation group defining the unit cell. See [`translation_group`](@ref).

# Description
This ensures the translation vector of g is reduced modulo translations in T,
bringing it to the canonical form within the unit cell.

# See Also
- [`floor_tol`](@ref): Used internally for tolerance-aware floor operations
"""
function mod!(g::sym_element, T::translation_group)
    nvec = floor_tol.(inv(T.basis) * g.gVec) # integer part
    g.gVec .= g.gVec - T.basis * nvec   
    return nothing
end

"""
    ==(g1::sym_element, g2::sym_element) -> Bool

Compare two symmetry elements for equality.

# Arguments
- `g1::sym_element`: First symmetry element. See [`sym_element`](@ref).
- `g2::sym_element`: Second symmetry element. See [`sym_element`](@ref).

# Returns
- `Bool`: `true` if elements are approximately equal (within tolerance 1e-12)

# Note
Equality is determined by comparing both the transformation matrix and 
translation vector using `isapprox` with a tolerance of 1e-12.

"""
function ==(g1::sym_element, g2::sym_element)::Bool
    return isapprox(g1.gVec, g2.gVec; atol = 1e-12)&& isapprox(g1.gMat,g2.gMat; atol = 1e-12)
end

"""
    ==(G1::sym_group, G2::sym_group) -> Bool

Compare two symmetry groups for equality.

# Arguments
- `G1::sym_group`: First symmetry group. See [`sym_group`](@ref).
- `G2::sym_group`: Second symmetry group. See [`sym_group`](@ref).

# Returns
- `Bool`: `true` if groups contain the same elements (possibly in different order)

# Description
Two groups are equal if they have the same number of elements and
every element in G1 is also found in G2 (implying the converse as well).

# See Also
- [`is_element`](@ref): Used internally to check element membership
"""
function ==(G1::sym_group, G2::sym_group)::Bool
    if G1.n_elements == G2.n_elements
        if all(x -> is_element(x, G2), G1.elements)
            return true
        end
    end
    return false
end

"""
    ^(g::sym_element, n::Int) -> sym_element

Compute the n-th power of a symmetry element by repeated composition.

# Arguments
- `g::sym_element`: Symmetry element. See [`sym_element`](@ref).
- `n::Int`: Power to raise the element to

# Returns
- `sym_element`: Result of applying `g` `n` times in succession

# Examples
```julia
# Get a 180° rotation from applying a 90° rotation twice
rot90 = sym_element([0.0 -1.0; 1.0 0.0], [0.0, 0.0])
rot180 = rot90^2
```

# Note
- When `n = 0`, returns the identity element
- For `n > 0`, composes `g` with itself `n` times

"""
function ^(g::sym_element, n::Int)::sym_element
    gout = g
    for i = 1:(n-1)
        gout = g ∘ gout  # Composition
    end
    if n == 0
        gout = neutral_elem(g)
    end
    return gout
end

"""
    neutral_elem(g::sym_element) -> sym_element
    neutral_elem(G::sym_group) -> sym_element

Returns the identity element of a symmetry element or group.

# Arguments
- `g::sym_element`: Reference symmetry element. See [`sym_element`](@ref).
- `G::sym_group`: Symmetry group. See [`sym_group`](@ref).

# Returns
- `sym_element`: Identity element (identity matrix and zero translation) with same dimension as the input

# Examples
```julia
# From a symmetry element
g = sym_element([0 1; -1 0], [1.0, 2.0])  # 2D rotation
id = neutral_elem(g)  # 2D identity element

```

"""
function neutral_elem(g::sym_element)::sym_element
    d = length(g.gVec)
    sym_element(Matrix(I, d, d), zeros(Float64, d))
end

function neutral_elem(G::sym_group)::sym_element
    return neutral_elem(G.elements[1])
end

"""
    ∘(g2::sym_element, g1::sym_element) -> sym_element

Group operation: composition of symmetry elements.

# Arguments
- `g2::sym_element`: Right-hand symmetry element. See [`sym_element`](@ref).
- `g1::sym_element`: Left-hand symmetry element. See [`sym_element`](@ref).

# Returns
- `sym_element`: Composition result (g2 ∘ g1)

# Mathematical Description
For the composition g2 ∘ g1:
- Result matrix = g2.gMat * g1.gMat
- Result vector = g2.gMat * g1.gVec + g2.gVec

# Examples
```julia
# Compose a rotation followed by translation
g1 = sym_element([0.0 -1.0; 1.0 0.0], [0.0, 0.0])  # Rotation
g2 = sym_element([1.0 0.0; 0.0 1.0], [1.0, 0.0])   # Translation
g3 = g2 ∘ g1  # Rotation followed by translation
```

# See Also
- [`^`](@ref): Power operation that uses composition internally
- [`inverse`](@ref): Related group operation
"""
function ∘(g2::sym_element, g1::sym_element)::sym_element
    gMat = g2.gMat * g1.gMat
    gVec = g2.gMat * g1.gVec + g2.gVec
    sym_element(gMat, gVec)
end

"""
    add_element!(g::sym_element, G::sym_group)

Adds symmetry element `g` to group `G` and updates its element count.

# Arguments
- `g::sym_element`: Element to add. See [`sym_element`](@ref).
- `G::sym_group`: Group to be modified. See [`sym_group`](@ref).

# Effects
- Adds `g` to G.elements
- Increments G.n_elements

"""
function add_element!(g::sym_element, G::sym_group)
    push!(G.elements, g)
    G.n_elements += 1
end

"""
    inverse(g1::sym_element) -> sym_element

Returns the inverse of symmetry element `g` such that g ∘ g⁻¹ = e.

# Arguments
- `g1::sym_element`: Symmetry element to invert. See [`sym_element`](@ref).

# Returns
- `sym_element`: Inverse element g⁻¹

# Mathematical Description
For a symmetry element g with matrix M and vector v:
- g⁻¹ has matrix M⁻¹
- g⁻¹ has vector -M⁻¹ * v

# Examples
```julia
g = sym_element([0.0 -1.0; 1.0 0.0], [1.0, 0.0])  # Rotation + translation
g_inv = inverse(g)  # Inverse transformation
g_inv ∘ g == neutral_elem(g)  # Returns True
```

"""
function inverse(g1::sym_element)
    gMat = transpose(g1.gMat)
    gVec = -transpose(g1.gMat) * g1.gVec
    sym_element(gMat, gVec)
end

"""
    commutator(g1::sym_element, g2::sym_element) -> sym_element

Computes the commutator of two symmetry elements.

# Arguments
- `g1::sym_element`: First symmetry element. See [`sym_element`](@ref).
- `g2::sym_element`: Second symmetry element. See [`sym_element`](@ref).

# Returns
- `sym_element`: Commutator g2⁻¹ ∘ g1⁻¹ ∘ g2 ∘ g1

# Mathematical Description
The commutator measures how far two elements are from commuting.
If g1 and g2 commute, their commutator equals the neutral element.

# Examples
```julia
# Check if two symmetry operations commute
comm = commutator(g1, g2)
if comm == neutral_elem(g1)
    println("g1 and g2 commute")
end
```

# See Also
- [`inverse`](@ref): Used internally to compute element inverses
"""
function commutator(g1::sym_element, g2::sym_element)
    g1_inv = inverse(g1)
    g2_inv = inverse(g2)
    g3 = g2_inv ∘ g1_inv ∘ g2 ∘ g1
    return g3
end

"""
    find_order(g::sym_element, T::translation_group) -> Int

Finds the smallest positive integer `n` such that `g^n = identity`.

# Arguments
- `g::sym_element`: Symmetry element. See [`sym_element`](@ref).
- `T::translation_group`: Translation group for modular arithmetic. See [`translation_group`](@ref).

# Returns
- `Int`: Order of the element

# Description
The order is the smallest power that gives the identity element.
For example, a 90-degree rotation has order 4, as four applications
return to the identity. Translation vectors are reduced modulo the unit cell.

# Throws
- Error if order > 20, which likely indicates a numerical error

# Examples
```julia
# Find the order of a rotation
T = translation_group([(1.0, 0.0), (0.0, 1.0)])
rot60 = sym_element([0.5 -sqrt(3)/2; sqrt(3)/2 0.5], [0.0, 0.0])
order = find_order(rot60, T)  # Should be 6
```

# See Also
- [`neutral_elem`](@ref): Identity element used for comparison
"""
function find_order(g::sym_element,T::translation_group)::Int
    e = neutral_elem(g)
    order = 0
    gn = e

    while true
        gn = g ∘ gn
        order += 1
        mod!(gn,T)
        if  gn == neutral_elem(g)
            return order
        end
        if order > 20
            throw(error("order of g > 20"))
        end
    end
end



"""
    generate_closed_basis(basis::sym_group, T::translation_group) -> sym_group

Generates an overcomplete basis of symmetry elements that is closed under commutation.

# Arguments
- `basis::sym_group`: Initial set of symmetry elements. See [`sym_group`](@ref).
- `T::translation_group`: Translation group for modular arithmetic. See [`translation_group`](@ref).

# Returns
- `sym_group`: Group containing all original elements plus necessary commutators

# Description
This function ensures that for any two elements g, h in the group,
their commutator [g,h] is also in the group. It iteratively adds
commutators until the group is closed under commutation.

# Throws
- Error if group size exceeds 100 elements, which may indicate an incorrect setup

# See Also
- [`commutator`](@ref): Function used to compute element commutators
- [`is_element`](@ref): Used to check if commutators are already in the group
- [`add_element!`](@ref): Used to add new commutators to the group
"""
function generate_closed_basis(basis::sym_group, T::translation_group)::sym_group
    Gnew = sym_group(copy(basis.elements))

    while true
        G = Gnew
        for (n, g) in enumerate(G.elements)
            for g2 in G.elements[n:end]
                h = commutator(g, g2)
                mod!(h, T)

                if !(is_element(h, G))
                    add_element!(h, Gnew)
                end
            end
        end

        if Gnew == G
            return G
        end

        if Gnew.n_elements > 100
            throw(error("group too large (>100 elements)"))
        end
    end
end

"""
    generate_symmetry_group(basis::sym_group, T::translation_group) -> sym_group

Generates the full symmetry group from a given basis of symmetry elements.

# Arguments
- `basis::sym_group`: Initial elements to generate from. See [`sym_group`](@ref).
- `T::translation_group`: Translation group for modular arithmetic. See [`translation_group`](@ref).

# Returns
- `sym_group`: Complete symmetry group containing all generated elements

# Description
This function creates the full group by:
1. Computing a commutation-closed basis
2. Taking all powers of each element up to its order
3. Computing all compositions between elements

The result is a group closed under both composition and commutation.

# Examples
```julia
# Generate the full point group from basic symmetry operations
C4 = sym_element([0 -1; 1 0], [0.0, 0.0])  # 90° rotation
σᵥ = sym_element([-1 0; 0 1], [0.0, 0.0])  # Reflection
basis = sym_group([neutral_elem(C4), C4, σᵥ])
T = translation_group([(1.0, 0.0), (0.0, 1.0)])
full_group = generate_symmetry_group(basis, T)  # D4 group with 8 elements
```

# See Also
- [`generate_closed_basis`](@ref): First step in group generation
- [`find_order`](@ref): Used to determine element orders for power computation
"""
function generate_symmetry_group(basis::sym_group, T::translation_group)::sym_group
    # First compute a commutation-closed basis
    for element in basis.elements
        mod!(element, T)
    end

    closed_basis = generate_closed_basis(basis, T)
    Gnew = sym_group(copy(closed_basis.elements))

    for g in closed_basis.elements
        G = Gnew
        order = find_order(g,T)
        for n in 0:order
            for g2 in G.elements
                gnew = g^n ∘ g2
                mod!(gnew, T)
                if !(is_element(gnew, G))
                    add_element!(gnew, Gnew)
                end
            end
        end
    end

    return Gnew
end

"""
    bond

Represents a bond (connection) between two points in the lattice.

# Fields
- `r1::Vector{Float64}`: Position of the first endpoint
- `r2::Vector{Float64}`: Position of the second endpoint

# Description
Bonds are typically used to represent connections between sites in a lattice,
such as nearest-neighbor connections in a crystal structure.

# Examples
```julia
# Create a bond between origin and point (1,0)
b = bond([0.0, 0.0], [1.0, 0.0])
```
"""
mutable struct bond
    r1     ::Vector{Float64}
    r2     ::Vector{Float64}
end

"""
    ==(bond1::bond, bond2::bond) -> Bool

Checks whether two bonds are equal.

# Arguments
- `bond1::bond`: First bond. See [`bond`](@ref).
- `bond2::bond`: Second bond. See [`bond`](@ref).

# Returns
- `Bool`: `true` if bonds are equivalent, `false` otherwise

# Description
Two bonds are considered equal if their endpoints match in either order:
- (r1, r2) equals (r1', r2')
- or (r1, r2) equals (r2', r1')

Comparison uses approximation with tolerance 1e-12 to handle floating-point errors.

# Examples
```julia
b1 = bond([0.0, 0.0], [1.0, 0.0])
b2 = bond([1.0, 0.0], [0.0, 0.0])
b1 == b2  # Returns true
```

"""
function ==(bond1::bond, bond2::bond)::Bool
    if isapprox(bond1.r1, bond2.r1; atol = 1e-12) && isapprox(bond1.r2, bond2.r2; atol = 1e-12)
        return true
    end
    if isapprox(bond1.r1 , bond2.r2; atol = 1e-12) && isapprox(bond1.r2, bond2.r1; atol = 1e-12)
        return true
    end
    return false
end

"""
    flip_bond!(b::bond)

Flips the order of endpoints in a bond, swapping r1 and r2.

# Arguments
- `b::bond`: Bond to be flipped (modified in place). See [`bond`](@ref).

# Description
This operation reverses the direction of the bond without changing
its geometric meaning.

# Examples
```julia
b = bond([0.0, 0.0], [1.0, 0.0])
flip_bond!(b)  # Now b is bond([1.0, 0.0], [0.0, 0.0])
```


"""
function flip_bond!(b::bond)
    r1 =  b.r1
    r2 =  b.r2
    b.r1 = r2
    b.r2 = r1
  end



"""
    ∘(g::sym_element, b::bond) -> bond

Applies a symmetry operation `g` to a bond `b`.

# Arguments
- `g::sym_element`: Symmetry element to apply. See [`sym_element`](@ref).
- `b::bond`: Bond to transform. See [`bond`](@ref).

# Returns
- `bond`: Transformed bond with both endpoints mapped by g

# Description
Transforms both endpoints of the bond according to the symmetry element:
- r1_new = g.gMat * b.r1 + g.gVec
- r2_new = g.gMat * b.r2 + g.gVec

# Examples
```julia
# Reflect a horizontal bond across y-axis
b = bond([0.0, 0.0], [1.0, 0.0])
g = sym_element([-1 0; 0 1], [0.0, 0.0])
b_reflected = g ∘ b  # Bond from origin to (-1,0)
```

"""
function ∘(g::sym_element, b::bond)::bond
    r1new = g.gMat * b.r1 + g.gVec
    r2new = g.gMat * b.r2 + g.gVec
    bond(r1new, r2new)
end

"""
    mod!(b::bond, T::translation_group, unitcell::UnitCell)

Translates a bond so that the first endpoint lies in the first unit cell.

# Arguments
- `b::bond`: Bond to be modified in place. See [`bond`](@ref).
- `T::translation_group`: Translation group defining the unit cell. See [`translation_group`](@ref).
- `unitcell::UnitCell`: Unit cell information. See [`UnitCell`](@ref).

# Description
Shifts both endpoints of the bond by the same translation vector,
such that r1 lies within the first unit cell. This preserves the
relative position between r1 and r2 while normalizing the bond position.

# See Also
- [`is_approximately_integer_vector`](@ref): Used to check if translation vectors are integer-valued
"""
function mod!(b::bond, T::translation_group, unitcell::UnitCell)
    nvec = b.r1
    for bas in unitcell.basis
        nvec = inv(T.basis) * (b.r1-collect(bas)) #get integer part  
        if is_approximately_integer_vector(nvec)
            break
        end
    end
    b.r1 .= b.r1 - T.basis * nvec     # Shift r1 into first unit cell
    b.r2 .= b.r2 - T.basis * nvec     # Shift r2 by the same amount to preserve relative position
end


"""
    is_approximately_integer_vector(vec; tol=1e-8) -> Bool

Checks if all components of a vector are approximately integers.

# Arguments
- `vec::AbstractVector{<:Float64}`: Vector to check
- `tol::Float64=1e-8`: Tolerance for approximation

# Returns
- `Bool`: `true` if all components are within tolerance of integers

# Examples
```julia
is_approximately_integer_vector([1.0000001, 2.0])  # Returns true
is_approximately_integer_vector([1.1, 2.0])        # Returns false
```
"""
function is_approximately_integer_vector(vec::AbstractVector{<:Float64}; tol=1e-8)
    return all(x -> isapprox(x, round(x); atol=tol), vec)
end

"""
    bond_matrix(lattice::Lattice, center_sites) -> Matrix{bond}

Constructs a matrix of all bonds between a set of center_sites and all sites in the lattice.

# Arguments
- `lattice::Lattice`: Lattice containing site positions. See [`Lattice`](@ref).
- `center_sites`: Indices of center_sites

# Returns
- `Matrix{bond}`: Matrix where each row corresponds to a center_sites, 
  and each column to a target site in the lattice

# See Also
- [`bond`](@ref): Structure representing connections between lattice sites
"""
function bond_matrix(lattice::Lattice, center_sites)
    mat = Matrix{bond}(undef, length(center_sites), lattice.length)

    for b in eachindex(center_sites), j in 1:lattice.length
        r1 = collect(lattice.sitePositions[center_sites[b]])
        r2 = collect(lattice.sitePositions[j])
        mat[b, j] = bond(r1, r2)
    end

    return mat
end

"""
    sym_reduced_lattice(lattice::Lattice, center_sites, G::sym_group, T::translation_group)
        -> (Dict, Vector{bond}, Dict)

Reduces the full list of bonds in the lattice using the provided symmetry group. 

# Arguments
- `lattice::Lattice`: The lattice object with site positions. See [`Lattice`](@ref).
- `center_sites`: Indices of reference sites to form initial bonds
- `G::sym_group`: Symmetry group to apply for reduction. See [`sym_group`](@ref).
- `T::translation_group`: Translation group for normalizing coordinates. See [`translation_group`](@ref).

# Returns
- `reduction_dict`: Dictionary mapping each full bond index to its representative bond index
- `bond_vec_red`: List of symmetry-inequivalent bonds (the reduced basis)
- `position_dict`: Dictionary mapping from reduced bond index to lattice site indices (origin, target)

# Description
This function identifies which bonds in the lattice are equivalent under the
symmetry operations in G, keeping only one representative from each equivalence class.
This reduces computational overhead by eliminating redundant calculations.

# Examples
```julia
# Reduce bonds using symmetry
red_dict, unique_bonds, pos_dict = sym_reduced_lattice(lattice, [1], point_group, T)
```

# See Also
- [`bond_matrix`](@ref): Creates the initial matrix of all bonds
- [`flip_bond!`](@ref): Used to consider bond direction equivalence
- [`mod!`](@ref): Used to normalize bond positions to the unit cell
"""
function sym_reduced_lattice(lattice::Lattice, center_sites, G::sym_group, T::translation_group)
    bmat = bond_matrix(lattice, center_sites)             # Matrix of all bonds
    bond_vec_red = copy(bmat[:])                          # Flattened list of all bonds
    reduction_dict = Dict()                               # Map from full bond index to reduced bond index
    position_dict = Dict()                                # Map from reduced bond index to actual site indices

    #remove duplicates inside the unit cell

    for (it, b) in enumerate(bond_vec_red)
        # Find original (row, col) location of bond in matrix
        orig_ind = findfirst(x -> x == b, bmat)
        push!(position_dict, it => (center_sites[orig_ind[1]], orig_ind[2]))
        

        for g in G.elements
            #find new element
            bnew = g ∘ b
            mod!(bnew, T,lattice.unitcell)  # Normalize to unit cell
            
            # check its index
            mat_ind = findall(x -> x == bnew, bmat)

           
            # Record symmetry equivalence
            for ind in  mat_ind
            push!(reduction_dict, ind => it)
            end

            if  b≠ bnew
                #remove the corresponding bonds from bond_vec_red, that have a higher index than the original bond
                todelete = findall(x -> x == bnew, bond_vec_red)
                filter!( x -> x > it,todelete)
                deleteat!(bond_vec_red,todelete)
            end

            #do the same for the fliped bond
            flip_bond!(bnew)

            mod!(bnew, T,lattice.unitcell)

            mat_ind = findall(x -> x == bnew, bmat)

            for ind in  mat_ind
            push!(reduction_dict, ind => it)
            end

            if  b≠ bnew
                todelete = findall(x -> x == bnew, bond_vec_red)
                filter!( x -> x > it,todelete)
                deleteat!(bond_vec_red,todelete)
            end

        end
        
    end

    return reduction_dict, bond_vec_red, position_dict
end

"""
    getSymmetryGroup(geometry::String) -> (sym_group, translation_group)

Creates symmetry group for a specified lattice geometry. 
Modify this function to add new lattice types.

# Arguments
- `geometry::String`: Name of the lattice geometry

# Returns
- `sym_group`: Symmetry group for the specified lattice. See [`sym_group`](@ref).
- `translation_group`: Translation group for the specified lattice. See [`translation_group`](@ref).

# Supported Geometries
- "chain": 1D chain with reflection symmetry
- "square": 2D square lattice with C4 symmetry
- "simple_cubic": 3D cubic lattice 
- "triang": 2D triangular lattice with C6 symmetry
- "kagome": 2D kagome lattice
- "pyrochlore": 3D pyrochlore lattice

# Throws
- Error if the requested geometry is not implemented

# See Also
- [`generate_symmetry_group`](@ref): Used to generate full groups from basis elements
- [`shiftRotation`](@ref): Used to create rotations around specific points (e.g., kagome)
"""
function getSymmetryGroup(geometry::String)

    if geometry == "chain" ### chain lattice
        a1 = (1, 0)
        a2 = (0, 1)

        Px = sym_element([-1 0; 0 1],[0,0])
        basis = sym_group([neutral_elem(Px),Px])
        translation_Group = translation_group([a1,a2])
        symmetry_Group = generate_symmetry_group(basis,translation_Group)

    elseif geometry == "square" ### Square lattice
        a1 = (1, 0)
        a2 = (0, 1)

        C_4 = sym_element([0 1; -1 0],[0,0])
        Px = sym_element([-1 0; 0 1],[0,0])

        basis = sym_group([neutral_elem(C_4),C_4,Px])
        translation_Group = translation_group([a1,a2])
        symmetry_Group = generate_symmetry_group(basis,translation_Group)

    elseif geometry == "simple_cubic" ### Square lattice
        a1 = (1, 0, 0)
        a2 = (0, 1 , 0)
        a3 = (0, 0 , 1)

        C_41 = sym_element([0 1 0; -1 0 0; 0 0 1],[0,0,0])
        C_42 = sym_element([0 0 1; 0 1 0; -1 0 0],[0,0,0])
        Px = sym_element([-1 0 0 ; 0 1 0; 0 0 1],[0,0,0])

        basis = sym_group([neutral_elem(C_41),C_41,C_42,Px])
        translation_Group = translation_group([a1,a2,a3])
        symmetry_Group = generate_symmetry_group(basis,translation_Group)

    elseif geometry == "triang" ### Square lattice
        a1 = (1/2, sqrt(3)/2)
        a2 = (1/2, -sqrt(3)/2)

        C_6 = sym_element([1/2 -sqrt(3)/2; sqrt(3)/2 1/2],[0,0])
        Px = sym_element([-1 0; 0 1],[0,0])
        basis = sym_group([neutral_elem(C_6),C_6,Px])
        translation_Group = translation_group([a1,a2])
        symmetry_Group = generate_symmetry_group(basis,translation_Group)

    elseif geometry == "kagome" ### Square lattice
        a1 = (1, sqrt(3))
        a2 = (1, -sqrt(3))

        C_6 = shiftRotation([1/2 -sqrt(3)/2; sqrt(3)/2 1/2],[-1,0]) #C6 rotation around center of hexagon in Kagome lattice. 
        Px = sym_element([-1 0; 0 1],[0,0])
        basis = sym_group([neutral_elem(C_6),C_6,Px])
        translation_Group = translation_group([a1,a2])
        symmetry_Group = generate_symmetry_group(basis,translation_Group)

    elseif geometry == "pyrochlore" ### Square lattice
        a1 = (0,1/2,1/2)
        a2 = (1/2,0,1/2)
        a3 = (1/2,1/2,0)
        translation_Group = translation_group([a1,a2,a3])

        C_6I = sym_element([0 -1 0 ; 0 0 -1 ; -1 0 0],[0,0,0]) #C6 rotoreflection. 
        S = sym_element([0 0 1 ; 0 -1 0 ; 1 0 0],[1/4,0,1/4])#Screw symmetry along (1,0,1) 
        basis = sym_group([neutral_elem(C_6I),C_6I,S])
        symmetry_Group = generate_symmetry_group(basis,translation_Group)

    
    else 
        throw(error("Symmetry group for geometry: " * geometry * " not yet implemented"))
    end

    ### create graph for the lattice and return
    return symmetry_Group,translation_Group
end

"""
    shiftRotation(R::Matrix{<:Number}, p::Vector{<:Number}) -> sym_element

Creates a symmetry element that rotates around a point p instead of the origin.

# Arguments
- `R::Matrix{<:Number}`: Rotation matrix around origin
- `p::Vector{<:Number}`: Center point for rotation

# Returns
- `sym_element`: Symmetry element representing rotation around point p

# Description
Takes a rotation R about a point p and returns a symmetry element with:
- The same rotation matrix R
- A translation vector p - R*p that ensures rotation happens around p

# Examples
```julia
# Create a 90° rotation around the point (1,0)
R = [0 -1; 1 0]  # 90° rotation matrix
p = [1.0, 0.0]   # Rotation center
sym = shiftRotation(R, p) # outputs sym_element([0.0 -1.0; 1.0 0.0], [1.0, -1.0])
```

# See Also
- [`getSymmetryGroup`](@ref): Uses this function for geometries like kagome
"""
function shiftRotation(R::Matrix{<:Number}, p::Vector{<:Number})::sym_element
   return  sym_element(R,p-R*p)
end

R = [0 -1; 1 0]  # 90° rotation matrix
p = [1.0, 0.0]   # Rotation center
sym = shiftRotation(R, p)